### ISSUE TITLE
Promisepay::InternalServerError when creating items

### ISSUE THREAD

**Issue by ngelx** [PromisePay/promisepay-ruby#35]
Hello, when i'm getting **Promisepay::InternalServerError** when trying to create an item. 

```
sidekiq_1      | 2017-01-07T04:57:32.480Z 10 TID-mvmnw WARN: Promisepay::InternalServerError: 
sidekiq_1      | 2017-01-07T04:57:32.480Z 10 TID-mvmnw WARN: /myapp/.bundle/gems/promisepay-1.2.0/lib/promisepay/client.rb:183:in `on_complete'
sidekiq_1      | /myapp/.bundle/gems/promisepay-1.2.0/lib/promisepay/client.rb:84:in `post'
sidekiq_1      | /myapp/.bundle/gems/promisepay-1.2.0/lib/promisepay/resources/item_resource.rb:49:in `create'
```

Any idea what is going on?

**Comment by ngelx** [comment]
Ok, after some time of debugging i've found that the problem was caused because the **fee_ids** did not exist on promisepay.

Seems to be an error in the promisepay API that crash when the fee item params is not valid. Any way to report the error back to them?

thanks

**Comment by gerdadecio** [comment]
Hi @ngelx, It seems that you are passing an incorrect type in the fee_ids field, it should be of String type (e.g https://reference.promisepay.com/#create-item). We've taken a note on this and have the error display in our upcoming release.

Thanks!
